### ISSUE TITLE
Integration is using deprecated `DEVICE_CLASS_*` constants

### ISSUE THREAD

**Issue by frenck** [NickM-27/swatch-hass-integration#11]
This custom integration uses deprecated `DEVICE_CLASS_*` constants in its codebase.

The `DEVICE_CLASS_*` constants have been deprecated and replaced in Home Assistant Core 2021.12 (over a year ago). I would highly suggest updating/migrating this integration to the new enums.

For example, for the device classes supported by the `sensor` platform, there is now a `SensorDeviceClass` enum. So if a sensor previously used the `DEVICE_CLASS_ENERGY` constant, it should now use `SensorDeviceClass.ENERGY`. Other platforms (like `binary_sensor`, and `number`) provide similar enumerations for their supported device classes.

The migration thus only consists of replacing constants with an enumeration member and is, therefore, very low impact and should be fairly straightforward.

If I can help resolve any questions regarding this change or migration, feel free to ask or respond to this issue. I'm happy to help!

Kindest regards,

../Frenck

**Comment by pafnow** [comment]
In the same topic, I get this warning message in my logger :

`DEVICE_CLASS_OCCUPANCY was used from swatch, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.OCCUPANCY instead, please create a bug report at https://github.com/NickM-27/swatch-hass-integration/issues`

**Comment by NickM-27** [comment]
thanks, sorry it took so long

**Comment by frenck** [comment]
Don't worry! Thanks for addressing @NickM-27 ❤️ 

../Frenck
