### ISSUE TITLE
Can't add integration with nabu-casa cloud instance of HA?

### ISSUE THREAD

**Issue by coltography** [NickM-27/swatch-hass-integration#12]
I get about as far as adding the integration, to configure it I get to the "URL you use to access Swatch (ie. http://ip.ad.dr.ess:4500/)" window.

I don't yet have a URL to access Swatch since I'm still adding it as an integration, so it's a little confusing.

I added my nabucasa URL and it errors out. What are we supposed to put there?

Additionally at the bottom of the read me it says "Please visit the [main Swatch documentation](https://github.com/NickM-27/swatch/) for full installation instructions of this integration." but there is no installation instructions.

**Comment by NickM-27** [comment]
The integration is separate from the addon, which you need to install first.
